// <auto-generated />
using System;
using ContextoDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContextoDB.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220408024112_Se agrego campo activo a usuarioRol")]
    partial class SeagregocampoactivoausuarioRol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContextoDB.Models.Catalogos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Clave = "admin",
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Clave = "user",
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("ContextoDB.Models.Catalogos.RolPagina", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PaginaId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.HasKey("RolId", "PaginaId");

                    b.HasIndex("PaginaId");

                    b.ToTable("RolesPagina");
                });

            modelBuilder.Entity("ContextoDB.Models.Catalogos.RolUsuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("RolesUsuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            RolId = 1,
                            Activo = false
                        });
                });

            modelBuilder.Entity("ContextoDB.Models.Catalogos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Lara",
                            Email = "julian_lara@html.com",
                            FechaRegistro = new DateTime(2022, 4, 7, 20, 41, 12, 328, DateTimeKind.Local).AddTicks(104),
                            Nombre = "Julián",
                            NombreUsuario = "Jlara",
                            Password = "agBsAGEAcgBhAA=="
                        });
                });

            modelBuilder.Entity("ContextoDB.Models.Seguridad.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Clave = "catalogo",
                            Icono = "Menu",
                            Nombre = "Catalogo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Clave = "seguridad",
                            Icono = "Menu",
                            Nombre = "Seguridad"
                        });
                });

            modelBuilder.Entity("ContextoDB.Models.Seguridad.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Paginas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Clave = "usuario",
                            Icon = "description",
                            MenuId = 1,
                            Nombre = "Usuario"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Clave = "rol",
                            Icon = "description",
                            MenuId = 1,
                            Nombre = "Rol"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Clave = "menu",
                            Icon = "menu",
                            MenuId = 2,
                            Nombre = "Menu"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Clave = "pagina",
                            Icon = "page",
                            MenuId = 2,
                            Nombre = "Pagina"
                        });
                });

            modelBuilder.Entity("ContextoDB.Models.Catalogos.RolPagina", b =>
                {
                    b.HasOne("ContextoDB.Models.Seguridad.Pagina", "Pagina")
                        .WithMany()
                        .HasForeignKey("PaginaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextoDB.Models.Catalogos.Rol", "Rol")
                        .WithMany("RolPagina")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagina");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ContextoDB.Models.Catalogos.RolUsuario", b =>
                {
                    b.HasOne("ContextoDB.Models.Catalogos.Rol", "Rol")
                        .WithMany("RolUsuario")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextoDB.Models.Catalogos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ContextoDB.Models.Seguridad.Pagina", b =>
                {
                    b.HasOne("ContextoDB.Models.Seguridad.Menu", "Menu")
                        .WithMany("Pagina")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ContextoDB.Models.Catalogos.Rol", b =>
                {
                    b.Navigation("RolPagina");

                    b.Navigation("RolUsuario");
                });

            modelBuilder.Entity("ContextoDB.Models.Seguridad.Menu", b =>
                {
                    b.Navigation("Pagina");
                });
#pragma warning restore 612, 618
        }
    }
}
